### ISSUE TITLE
[BUG] Sparse Embedding Function are not working

### ISSUE THREAD

**Issue by dudeperf3ct** [milvus-io/milvus-model#25]
I am facing an `index out of range` error when running sparse embedding model example code shown below.

```python
from pymilvus import model
splade_ef = model.sparse.SpladeEmbeddingFunction(
    model_name="naver/splade-cocondenser-selfdistil", device="cpu"
)
docs = [
    "Artificial intelligence was founded as an academic discipline in 1956.",
    "Alan Turing was the first person to conduct substantial research in AI.",
    "Born in Maida Vale, London, Turing was raised in southern England.",
]
docs_embeddings = splade_ef.encode_documents(docs)
print(docs_embeddings)
```

Error stack trace

```bash
Traceback (most recent call last):
  File "/home/username/innovation-rag-search-retrieval /t.py", line 13, in <module>
    docs_embeddings = splade_ef.encode_documents(docs)
  File "/home/username/.cache/pypoetry/virtualenvs/rag-search-retrieval-hVw0f43b-py3.10/lib/python3.10/site-packages/milvus_model/sparse/splade.py", line 79, in encode_documents
    return self._encode(
  File "/home/username/.cache/pypoetry/virtualenvs/rag-search-retrieval-hVw0f43b-py3.10/lib/python3.10/site-packages/milvus_model/sparse/splade.py", line 84, in _encode
    return self.model.forward(texts, k_tokens=k_tokens)
  File "/home/username/.cache/pypoetry/virtualenvs/rag-search-retrieval-hVw0f43b-py3.10/lib/python3.10/site-packages/milvus_model/sparse/splade.py", line 153, in forward
    return vstack(sparse_embs).tocsr()
  File "/home/username/.cache/pypoetry/virtualenvs/rag-search-retrieval-hVw0f43b-py3.10/lib/python3.10/site-packages/scipy/sparse/_construct.py", line 779, in vstack
    return _block([[b] for b in blocks], format, dtype)
  File "/home/username/.cache/pypoetry/virtualenvs/rag-search-retrieval-hVw0f43b-py3.10/lib/python3.10/site-packages/scipy/sparse/_construct.py", line 912, in _block
    A = _compressed_sparse_stack(blocks[:, 0], 0, return_spmatrix)
  File "/home/username/.cache/pypoetry/virtualenvs/rag-search-retrieval-hVw0f43b-py3.10/lib/python3.10/site-packages/scipy/sparse/_construct.py", line 596, in _compressed_sparse_stack
    constant_dim = blocks[0].shape[other_axis]
IndexError: tuple index out of range
```

Library versions : `pymilvus` and `milvus-model`

```bash
poetry show pymilvus

 name         : pymilvus              
 version      : 2.4.4                 
 description  : Python Sdk for Milvus 

dependencies
 - environs <=9.5.0
 - grpcio >=1.49.1,<=1.63.0
 - milvus-lite >=2.4.0,<2.5.0
 - milvus-model >=0.1.0
 - pandas >=1.2.4
 - protobuf >=3.20.0
 - setuptools >=67
 - ujson >=2.0.0

required by
 - llama-index-vector-stores-milvus >=2.3.6,<3.0.0
```

```bash
poetry show milvus-model

 name         : milvus-model                                             
 version      : 0.2.3                                                    
 description  : Model components for PyMilvus, the Python SDK for Milvus 

dependencies
 - numpy *
 - onnxruntime *
 - protobuf *
 - scipy >=1.10.0
 - transformers >=4.36.0

required by
 - pymilvus >=0.1.0
```

**Comment by wxywb** [comment]
When I use scipy==1.14.0, I get the same error. There seems to be a break of 1D sparse vector stacking after scipy==1.13.0.
https://github.com/scipy/scipy/issues/21064

**Comment by xiaofan-luan** [comment]
do we need to fix anything?

**Comment by wxywb** [comment]
> do we need to fix anything?

scipy has fixed this this 1D sparse vector vstack/hstack bug. I will also modify this code in the next update for compatiablity.

**Comment by wxywb** [comment]
latest version has solved this problem.
